template = '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: packer
  name: packer
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: hashicorp/packer
    name: packer
'''

def buildNUMBER = env.BUILD_NUMBER


if (env.BRANCH_NAME == "main") {
    hello = "us-east-1"
    kaizen = "t2.micro"
}

else if (env.BRANCH_NAME == "qa") {
    hello = "us-east-2"
    kaizen = "t3.micro"
}

else if (env.BRANCH_NAME == "dev") {
    hello = "us-west-1"
    kaizen = "t2.small"
}

else {
    error "Branch doesn't match"
}


podTemplate(cloud: 'kubernetes', label: 'packer', showRawYaml: false, yaml: template){
node("packer"){
container("packer"){
stage ("Checkout SCM") {
        git branch: 'main', url: 'https://github.com/kaizenacademy/jenkins.git'
    }

withCredentials([usernamePassword(credentialsId: 'aws-creds', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
    withEnv(["AWS_REGION=${hello}"]) {
    stage ("Packer build") {
    sh """
    cd packer
    packer init .
    packer build -var jenkins_build_number=${buildNUMBER} packer.pkr.hcl
    """
    build job: 'hello-world',
    parameters: [
        string(name: 'action', value: 'apply'), 
        string(name: 'region', value: "${hello}"), 
        string(name: 'ami_id', value: "my-ami-${buildNUMBER}"), 
        string(name: 'az', value: "${hello}b"), 
        string(name: 'type', value: "${kaizen}")
        ]
}
}
}
}
}
}
